In [ ]:
#Q1

In [1]:
import numpy as np
print(np.__version__)

1.19.1


# 2. How to create a 1D array?


In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
#custom

test = np.arange(0,5001, 100)
test

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000,
       1100, 1200, 1300, 1400, 1500, 1600, 1700, 1800, 1900, 2000, 2100,
       2200, 2300, 2400, 2500, 2600, 2700, 2800, 2900, 3000, 3100, 3200,
       3300, 3400, 3500, 3600, 3700, 3800, 3900, 4000, 4100, 4200, 4300,
       4400, 4500, 4600, 4700, 4800, 4900, 5000])

# 3. How to create a boolean array?

In [7]:
np.full((3, 3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [8]:
np.full((5,5), False, dtype = bool)


array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

# 4. How to extract items that satisfy a given condition from 1D array?

In [10]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr %2 != 0]


array([1, 3, 5, 7, 9])

In [11]:
#custom
#Even Number

test = np.array(np.arange(50,101))
test[test %2 ==0 ]

array([ 50,  52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,
        76,  78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

# 5. How to replace items that satisfy a condition with another value in numpy array?

In [12]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [28]:
#custom

test = np.array(np.random.randint(1,100,80))
test[test % 3 == 0] = -1
test

array([76, 67, -1, -1,  5, -1, -1, -1, 52, -1, -1, 79, 85, 67,  8, 80, -1,
       25, -1, 89, -1, 76, 55, 37, 29, 10, -1, -1, -1, 31, 97,  8, 13, -1,
       17, 77, 49, 31, -1, 52, 61,  5, 37, 10, 86, 94, -1, 41, -1, -1, -1,
       23, 94,  2, 94, 65, 26, -1, -1, 14, -1, 64, 67,  4, -1, 20, 35, -1,
       62, -1, 74, -1, 88, -1, 13, 94, 64, -1, 23, 41])

# 6. How to replace items that satisfy a condition without affecting the original array?


In [29]:
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [30]:
#custom

test = np.arange(10,21)
new_test = np.where(test %2 == 1, -1, test)
print(test)
new_test

[10 11 12 13 14 15 16 17 18 19 20]


array([10, -1, 12, -1, 14, -1, 16, -1, 18, -1, 20])

# 7. How to reshape an array?

In [31]:
arr = np.arange(10)
arr.reshape(2, -1) 

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [32]:
#custom


test = np.linspace(0,10,100).reshape(10, -1)
test

array([[ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
         0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091],
       [ 1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
         1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192],
       [ 2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
         2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293],
       [ 3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
         3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394],
       [ 4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
         4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495],
       [ 5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
         5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596],
       [ 6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
         6.56565657,  6.66666667,  6.76767677

#  8. How to stack two arrays vertically?

In [34]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.concatenate([a, b], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [35]:
np.vstack([a, b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [36]:
np.r_[a, b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [43]:
#custom

np.concatenate([(np.linspace(-100, 0, 50).reshape(5,-1)), (np.random.randn(50).reshape(5, -1))], axis = 0)

array([[-1.00000000e+02, -9.79591837e+01, -9.59183673e+01,
        -9.38775510e+01, -9.18367347e+01, -8.97959184e+01,
        -8.77551020e+01, -8.57142857e+01, -8.36734694e+01,
        -8.16326531e+01],
       [-7.95918367e+01, -7.75510204e+01, -7.55102041e+01,
        -7.34693878e+01, -7.14285714e+01, -6.93877551e+01,
        -6.73469388e+01, -6.53061224e+01, -6.32653061e+01,
        -6.12244898e+01],
       [-5.91836735e+01, -5.71428571e+01, -5.51020408e+01,
        -5.30612245e+01, -5.10204082e+01, -4.89795918e+01,
        -4.69387755e+01, -4.48979592e+01, -4.28571429e+01,
        -4.08163265e+01],
       [-3.87755102e+01, -3.67346939e+01, -3.46938776e+01,
        -3.26530612e+01, -3.06122449e+01, -2.85714286e+01,
        -2.65306122e+01, -2.44897959e+01, -2.24489796e+01,
        -2.04081633e+01],
       [-1.83673469e+01, -1.63265306e+01, -1.42857143e+01,
        -1.22448980e+01, -1.02040816e+01, -8.16326531e+00,
        -6.12244898e+00, -4.08163265e+00, -2.04081633e+00,
         0.

In [46]:
np.vstack([np.random.randint(1,100,20).reshape(4, -1), np.ones((4,5))])

array([[81., 57., 67., 59., 22.],
       [33., 65., 41., 64., 53.],
       [49., 39., 34., 54., 19.],
       [20., 93.,  7., 11., 16.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [48]:
np.r_[np.eye((5)), np.zeros((5,5)), np.eye((5))]


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# 9. How to stack two arrays horizontally?


In [49]:
a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)

np.concatenate([a,b], axis = 1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [50]:
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [51]:
np.c_[a,b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [52]:
#custom

np.concatenate([(np.linspace(-100, -50, 10).reshape(2,-1)), (np.random.randn(10).reshape(2, -1))], axis = 1)


array([[-100.        ,  -94.44444444,  -88.88888889,  -83.33333333,
         -77.77777778,   -2.27640241,   -0.96528077,    0.78885917,
          -1.16142273,   -0.90117131],
       [ -72.22222222,  -66.66666667,  -61.11111111,  -55.55555556,
         -50.        ,    1.03508055,   -1.00680004,    0.35566627,
          -0.46115574,   -1.03123798]])

In [54]:
np.hstack([np.random.rand(1,100,20).reshape(4, -1), np.zeros((4,5))])

array([[0.31909755, 0.64271575, 0.17769736, ..., 0.        , 0.        ,
        0.        ],
       [0.77143487, 0.89622676, 0.59089824, ..., 0.        , 0.        ,
        0.        ],
       [0.81320763, 0.99301878, 0.45734231, ..., 0.        , 0.        ,
        0.        ],
       [0.96749163, 0.01828052, 0.36860686, ..., 0.        , 0.        ,
        0.        ]])

In [67]:
np.c_[np.arange(10).reshape(2,-1) , np.arange(21,31).reshape(2,-1)]

array([[ 0,  1,  2,  3,  4, 21, 22, 23, 24, 25],
       [ 5,  6,  7,  8,  9, 26, 27, 28, 29, 30]])

# 10. How to generate custom sequences in numpy without hardcoding?


In [70]:
a = np.array([1,2,3])

np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [72]:
#custom

b= np.array([1,3,5,7,9])
np.r_[np.repeat(b,5), np.tile(b, 5)]

array([1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 5, 5, 5, 5, 5, 7, 7, 7, 7, 7, 9, 9,
       9, 9, 9, 1, 3, 5, 7, 9, 1, 3, 5, 7, 9, 1, 3, 5, 7, 9, 1, 3, 5, 7,
       9, 1, 3, 5, 7, 9])